import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/verification.module.css'

import logo from '../assets/img/logo2.png';
import user from '../assets/img/user.svg';

import { Input } from 'semantic-ui-react'
import CardSlider from "../Components/cardSlider"
import CardBanner from "../Components/cardBanner"
import CategorySliderCard from "../Components/CategorySliderCard"


import 'react-phone-input-2/lib/style.css'
import { useState } from 'react'
import OurServicesCard from '@/Components/OurServicesCard';
import Testimonial from '@/Components/Testimonial';
const inter = Inter({ subsets: ['latin'] })

export default function Main() {
  const [phone, setphone] = useState("us")
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{backgroundColor:"#EDEDED"}}>
      <div className=' w-80 d-flex justify-content-between align-items-center flex-row  m-4'>
      <Image
            //  className="w-20"
            src={logo}
            alt="Next.js Logo"
            width={35}
            height={30}
            priority
          />
          <div className='text-primary  m-0' style={{textAlign:"center"}}>
          
          <Image
            //  className="w-20"
            src={user}
            alt="Next.js Logo"
            width={35}
            height={30}
            priority
          />
          </div>
      </div>
   
      <div className='d-flex justify-content-center align-items-center flex-column'>
      <Input icon='search' iconPosition='left' className='w-80 mb-2 mt-2' placeholder='Search users...' />
<CardSlider/>
<h4 className='w-80 align-start m-0 pt-2 pb-2'>LBig deals</h4>
<CardBanner/>
<h4 className='w-80 align-start mt-2 mb-2 m-0 pt-3 pb-2'>Categories.</h4> 

<div className='w-80 mt-3 d-flex justify-content-between align-items-center flex-row '
 style={{
}}>
<CategorySliderCard/>
<CategorySliderCard/>
<CategorySliderCard/>
<CategorySliderCard/>

</div>
<h4 className='w-80 align-start m-0 pt-3 pb-2'>Our services.</h4> 

<div className='w-80 mt-3 d-flex justify-content-between align-items-center flex-row '
 >

  
<OurServicesCard/>
<OurServicesCard/>
<OurServicesCard/>
</div>

<Testimonial/>
      </div>
     

    
     
      </main>
    </>
  )
}
