import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.css";
import logo from "../assets/img/logo.png";
import welcome from "../assets/img/welcome.png";
import ReactPhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/style.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import { GetHotels, GetRooms, loginUser } from "../Apis/Auth";
import frame from "../assets/desk/Frame.png";
import well from "../assets/desk/well.png";
import { useRouter } from "next/router";

export default function Home() {
  const [password, setpassword] = useState("");
  const router = useRouter();

  const [hotels, setHotels] = useState([]);
  const [rooms, setRooms] = useState([]);

  const submit = async () => {
    const res = await loginUser({ password, phone });
    if (res.token) {
      router.push("/");
    }
  };
  const [phone, setphone] = useState("us");
  function handleOnChange(value) {
    setphone(value);
  }
  return (
    <div className=" text-center" style={{ backgroundColor: "white" }}>
      <div className="row">
        <div className="d-sm-none p-0">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <div className={styles.background}>
              <Image
                className={styles.logo}
                src={logo}
                alt="Next.js Logo"
                width={200}
                height={55}
                priority
              />
              <Image
                className={styles.welcome}
                src={welcome}
                alt="Next.js Logo"
                width={100}
                height={37}
                priority
              />
            </div>
            <div className="d-flex justify-content-center align-items-center flex-column">
              <h3 className="mt-3 fs-3">Welcome to Well+ pharmacy</h3>
              <h5
                style={{ color: "#DD1717", marginTop: "0", fontSize: "18px" }}
              >
                live healthy … live well
              </h5>
            </div>
            <div
              className="d-flex justify-content-center align-items-center flex-column mt-4"
              style={{
                backgroundColor: "rgba(15, 67, 146, 0.07)",
                width: "90%",
                height: "290px",
                borderRadius: "15px",
              }}
            >
              <h2 style={{ color: "#0F4392" }} className="m-2">
                Sign in
              </h2>
              <div className="d-flex justify-content-center align-items-center mt-2">
                <span>Don't have an account?</span>
                <Link href={"/register"}>
                  <p className="ms-2">Sign up</p>
                </Link>
              </div>
              <form className="text-start d-flex justify-content-center flex-column w-100 px-4">
                <div className="form-group mt-3">
                  <label htmlFor="phone">Phone Number*</label>
                  <ReactPhoneInput
                    defaultCountry={"us"}
                    className="mt-2 font-sm-16"
                    value={phone}
                    onChange={handleOnChange}
                    id="phone"
                  />
                </div>
                <div className="form-group mt-3">
                  <label htmlFor="password">Password*</label>
                  <input
                    type="password"
                    className="form-control mt-3 font-sm-16 py-2"
                    id="password"
                    placeholder="Write here"
                  />
                </div>
                <div className="form-check d-flex justify-content-between align-items-center">
                  <div className="remember-me">
                    <input
                      type="checkbox"
                      className="form-check-input"
                      id="remember-me"
                    />
                    <label htmlFor="remember-me" className="form-check-label">
                      Remember me
                    </label>
                  </div>
                  <Link href="/" className="forget-password">
                    <span className="text-primary fs-5 fw-bold">
                      Forget password
                    </span>
                  </Link>
                </div>
              </form>
            </div>
          </main>
          <Link
            href="/verification"
            className="w-100 position-fixed bottom-0 start-0 bg-white pt-2 pb-3 px-4"
            style={{
              boxShadow: "0px -18px 40px 0px #0000001F",
            }}
          >
            <button
              type="button"
              onClick={submit}
              className="btn btn-primary mt-3 w-100"
            >
              Next
            </button>
          </Link>
        </div>
        <div className="d-none d-md-block">
          <div
            className="d-flex justify-content-center align-items-center"
            style={{ minHeight: "100vh" }}
          >
            <div className="divlogosignup">
              <Image
                style={{
                  width: "381px",
                  height: "122px",
                }}
                src={well}
                alt="Next.js Logo"
                priority
              />

              <Image
                style={{
                  width: "594px",
                  height: "444px",
                }}
                src={frame}
                alt="Next Logo"
                priority
              />
            </div>

            <div className="divsignup d-flex justify-content-end align-items-center flex-column">
              <div className="d-flex justify-content-center align-items-center flex-column">
                <h4 className="m-3 font-xs-16 fw-bold">
                  Welcome to Well+ pharmacy
                </h4>
                <h5
                  style={{
                    color: "#DD1717",
                    fontWeight: "400",
                    marginBottom: "10px",
                  }}
                >
                  live healthy … live well
                </h5>
              </div>
              <div
                className="d-flex justify-content-center align-items-center flex-column mt-4"
                style={{
                  backgroundColor: "rgba(15, 67, 146, 0.07)",
                  width: "487px",
                  borderRadius: "15px",
                  height: "380px",
                }}
              >
                <h2 style={{ color: "#0F4392" }}>Sign in</h2>
                <div className="d-flex justify-content-center align-items-center w-100">
                  <span>Don't have an account?</span>

                  <Link href={"/register"}>
                    <p className="m-2 fw-bold">Sign up</p>
                  </Link>
                </div>

                <form className="d-flex justify-content-center flex-column w-100 px-4">
                  <div className="form-group mt-2">
                    <label htmlFor="phone">Phone Number*</label>
                    <ReactPhoneInput
                      country={"ng"}
                      className="mt-3 font-sm-16"
                      value={phone}
                      onChange={handleOnChange}
                      id="phone"
                    />
                  </div>
                  <div className="form-group mt-3">
                    <label htmlFor="password">Password*</label>
                    <input
                      type="password"
                      className="form-control mt-3 font-sm-16 py-2"
                      id="password"
                      placeholder="Write here"
                    />
                  </div>
                  <div className="form-check d-flex justify-content-between align-items-center">
                    <div className="remember-me">
                      <input
                        type="checkbox"
                        className="form-check-input"
                        id="remember-me"
                      />
                      <label htmlFor="remember-me" className="form-check-label">
                        Remember me
                      </label>
                    </div>
                    <Link href="/" className="forget-password">
                      <span className="text-primary fs-5 fw-bold">
                        Forget password
                      </span>
                    </Link>
                  </div>
                  <Link href="/verification" className="w-100">
                    <button
                      type="button"
                      onClick={submit}
                      className="btn btn-primary mt-3 w-100"
                    >
                      Next
                    </button>
                  </Link>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
