import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/verification.module.css'

import verification from '../assets/img/verification.png';
import Left from '../assets/img/Left.png';
import user from '../assets/img/user.svg';
import starTerible from '../assets/img/star_terrible.png';
import starBad from '../assets/img/star_bad.png';
import starGood from '../assets/img/star_good.png';
import startOk from '../assets/img/star_ok.png';
import starGreat from '../assets/img/star_great.png';
import upload from '../assets/img/arrow_up.png';
import Modal from "../Components/Requests/ModalExampleModal"
import 'react-phone-input-2/lib/style.css'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [phone, setphone] = useState("us")
  const [open, setOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className='d-flex justify-content-around align-items-around flex-row w-100 m-4'>
      <Image
            //  className="w-20"
            src={Left}
            alt="Next.js Logo"
            width={35}
            height={30}
            priority
          />
          <h3 className='text-primary w-60 m-0' style={{textAlign:"center"}}>
          Write a review
          </h3>
          <Image
            //  className="w-20"
            src={user}
            alt="Next.js Logo"
            width={35}
            height={30}
            priority
          />
      </div>
      <h3>Rate your experience</h3>
      <div className={"d-flex justify-content-around align-items-around flex-row"}>
       
           <Image
            src={starTerible}
            alt="Next.js Logo"
            // width={80}
            // height={37}
            priority
          />
           <Image
            src={starBad}
            alt="Next.js Logo"
            // width={80}
            // height={37}
            priority
          />
           <Image
            src={startOk}
            alt="Next.js Logo"
            // width={80}
            // height={37}
            priority
          />
           <Image
            src={starGood}
            alt="Next.js Logo"
            // width={80}
            // height={37}
            priority
          /> <Image
          src={starGreat}
          alt="Next.js Logo"
          // width={80}
          // height={37}
          priority
        />
      </div>
      <div className='d-flex justify-content-center align-items-center flex-column w-80 mt-5'>
      <div className="form-group w-100">
    <label htmlFor="exampleFormControlTextarea1">Leave your message*</label>
    <textarea className="form-control" id="exampleFormControlTextarea1" rows={3}></textarea>
  </div>
  <p className='w-100 m-0 mt-2'>Upload a file</p>
  <div className='d-flex justify-content-center align-items-center flex-column box-grey'>
  <Image
            src={upload}
            alt="Next.js Logo"
            // width={80}
            // height={37}
            priority
          />
          <div className='d-flex justify-content-center align-items-center flex-column box-grey-20 '>
            Add Files
          </div>
          <p className='text-muted m-2'>Or drop files to upload</p>
  </div>
  <button onClick={()=>setOpen(true)} type="submit" className="btn btn-primary mb-3 mt-3 w-100">Submit</button>

      </div>
    
<Modal setOpen={setOpen} open={open}/>

     
      </main>
    </>
  )
}
